import React, { useCallback, useEffect, useState } from "react";
import CodeDisplay from "./code_display";

type Props = {};

const expressions = [
  "(Div(Stylewidth:2px)(P'2'))",
  "(Div(Stylewidth:2px)(P'12'))",
  "(Div(Stylewidth:2px)(Compose(Div(Stylewidth:100%)(P'24'))(Compose(P'9')(Compose(Compose(Div(Stylemargin-right:2%)(Compose(Compose(P'100')(P'100'))(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'24')))(Compose(P'24')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Stylewidth:2px)(Compose(Div(Stylewidth:100%)(P'24'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Stylemargin-right:2%)(Compose(Compose(P'100')(P'100'))(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'24')))(Compose(P'24')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Stylewidth:2px)(Compose(Div(Stylewidth:100%)(P'24'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Styleborder:24%green)(Compose(P'50')(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'24')))(Compose(P'24')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junct(Junctborder:50pxblue(Junctmargin-right:100pxheight:3px))margin-left:auto))(Compose(Div(Stylemargin-left:auto)(P'24'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Styleborder:24%green)(Compose(P'50')(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'12')))(Compose(P'F')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junctmargin-top:autowidth:100%))(Compose(Div(Style(Junctborder:3%bluewidth:100px))(Compose(P'100')(P'100')))(Compose(P'100')(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:100%(Junctmargin-left:automargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:2pxmargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctborder:24%bluewidth:2px))(Compose(Div(Style(Junctborder:3pxbluewidth:5%))(P'36'))(Compose(Div(Stylewidth:24%)(P'F'))(Compose(Compose(Div(Style(Junctmargin-right:100%(Junctwidth:50%(Junctmargin-left:8pxmargin-right:auto))))(Compose(P'100')(Compose(P'100')(Compose(P'12')(Compose(P'100')(P'100'))))))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxmargin-right:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:A%margin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctborder:24pxbluewidth:2px))(Compose(Div(Style(Junctborder:3pxbluewidth:5%))(P'36'))(Compose(Div(Stylewidth:24%)(P'F'))(Compose(Compose(Div(Style(Junctmargin-right:100%(Junctwidth:50%(Junctmargin-left:8pxmargin-right:auto))))(Compose(P'100')(Compose(P'100')(Compose(P'12')(Compose(P'100')(P'100'))))))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxmargin-right:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:A%margin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctborder:24pxbluewidth:2px))(Compose(Div(Style(Junctborder:3pxbluewidth:5%))(P'36'))(Compose(Div(Styleheight:50%)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-left:8pxmargin-right:auto))))(Compose(P'100')(Compose(P'100')(Compose(P'100')(Compose(P'100')(P'100'))))))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxmargin-right:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:A%margin-right:auto))))(P'12')))))))",
  "(Div(Style(Junct(Junctborder:50pxblue(Junctmargin-right:100pxheight:3px))(Junctmargin-right:8%(Junctwidth:1%(Junctwidth:2px(Junctborder:100%greenheight:24%))))))(Compose(Div(Stylemargin-left:auto)(P'24'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Styleborder:24%green)(Compose(P'F')(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'12')))(Compose(P'F')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junct(Junctborder:50pxblue(Junctmargin-right:100pxheight:3px))margin-left:auto))(Compose(Div(Stylemargin-left:auto)(P'24'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Styleborder:24%green)(Compose(P'F')(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'12')))(Compose(P'F')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junct(Junctborder:50pxblue(Junctmargin-right:100pxheight:3px))(Junctmargin-right:8%(Junctwidth:1%(Junctwidth:2px(Junctborder:100%greenheight:24%))))))(Compose(Div(Stylemargin-left:auto)(P'12'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'F')(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'12')))(Compose(P'F')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junctheight:50pxwidth:100%))(Compose(Div(Stylemargin-left:auto)(P'12'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'F')(Compose(P'100')(Compose(P'50')(Compose(Compose(P'100')(Compose(P'100')(P'12')))(Compose(P'F')(P'12')))))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junctheight:50pxwidth:100%))(Compose(Div(Stylemargin-left:auto)(P'12'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'F')(Compose(P'100')(P'24'))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junctheight:50pxwidth:100%))(Compose(Div(Stylemargin-left:auto)(P'12'))(Compose(Div(Stylemargin-left:36px)(P'100'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'F')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:Fpx)))(P'8')))(Compose(P'100')(Compose(Compose(Compose(Compose(P'100')(P'100'))(Compose(P'100')(P'100')))(Compose(Compose(P'100')(Compose(P'8')(P'100')))(P'B')))(P'100')))))))",
  "(Div(Style(Junctheight:50pxwidth:100%))(Compose(Div(Stylemargin-left:auto)(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'F')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:2px(Junctmargin-left:auto(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctheight:50pxwidth:100%))(Compose(Div(Stylemargin-left:auto)(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:2px(Junctmargin-left:auto(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctheight:50pxwidth:100%))(Compose(Div(Stylemargin-left:auto)(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:2px(Junctmargin-left:auto(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctheight:50pxwidth:100%))(Compose(Div(Style(Junctborder:3pxbluemargin-left:9px))(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:2px(Junctmargin-left:auto(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctheight:50%width:100%))(Compose(Div(Style(Junctborder:3pxbluewidth:100%))(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-top:24pxmargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:50pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctborder:2pxgreenwidth:100%))(Compose(Div(Style(Junctborder:3pxbluewidth:100%))(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-left:automargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctborder:2pxgreenwidth:100%))(Compose(Div(Style(Junctborder:3pxbluewidth:100%))(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-left:automargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctborder:2pxgreenwidth:100%))(Compose(Div(Style(Junctborder:3pxbluewidth:100%))(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-left:automargin-right:auto))))(Compose(P'100')(P'F')))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
  "(Div(Style(Junctborder:2pxgreenwidth:100%))(Compose(Div(Style(Junctborder:3pxbluewidth:100%))(P'12'))(Compose(Div(Stylemargin-left:36px)(P'F'))(Compose(Compose(Div(Style(Junctborder:2pxblue(Junctwidth:50%(Junctmargin-left:automargin-right:auto))))(Compose(P'100')(Compose(P'100')(P'100'))))(Div(Style(Junctwidth:24%(Junctmargin-right:8pxmargin-left:auto)))(P'8')))(Div(Style(Junctborder:2pxred(Junctmargin-top:50pxwidth:100%)))(Div(Style(Junctwidth:24%(Junctheight:24px(Junctmargin-left:automargin-right:auto))))(P'12')))))))",
];
const html_expressions = [
  "<html><body><div style='width: 2px'><p>Lo</p></div></body></html>",
  "<html><body><div style='width: 2px'><p>Lorem IpsumL</p></div></body></html>",
  "<html><body><div style='width: 2px'><div style='width: 100%'><p>Lorem IpsumLorem IpsumLo</p></div><p>Lorem Ips</p><div style='margin-right: 2%'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLo</p><p>Lorem IpsumLorem IpsumLo</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='width: 2px'><div style='width: 100%'><p>Lorem IpsumLorem IpsumLo</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='margin-right: 2%'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLo</p><p>Lorem IpsumLorem IpsumLo</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='width: 2px'><div style='width: 100%'><p>Lorem IpsumLorem IpsumLo</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 24% solid green'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLo</p><p>Lorem IpsumLorem IpsumLo</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='border: 50px solid blue; margin-right: 100px; height: 3px; margin-left: auto'><div style='margin-left: auto'><p>Lorem IpsumLorem IpsumLo</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 24% solid green'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumL</p><p>Lorem IpsumLore</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='margin-top: auto; width: 100%'><div style='border: 3% solid blue; width: 100px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><div style='border: 2px solid blue; width: 100%; margin-left: auto; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 24%; height: 24px; margin-left: 2px; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 24% solid blue; width: 2px'><div style='border: 3px solid blue; width: 5%'><p>Lorem IpsumLorem IpsumLorem IpsumLor</p></div><div style='width: 24%'><p>Lorem IpsumLore</p></div><div style='margin-right: 100%; width: 50%; margin-left: 8px; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; margin-right: 100%'><div style='width: 24%; height: 24px; margin-left: 10%; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 24px solid blue; width: 2px'><div style='border: 3px solid blue; width: 5%'><p>Lorem IpsumLorem IpsumLorem IpsumLor</p></div><div style='width: 24%'><p>Lorem IpsumLore</p></div><div style='margin-right: 100%; width: 50%; margin-left: 8px; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; margin-right: 100%'><div style='width: 24%; height: 24px; margin-left: 10%; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 24px solid blue; width: 2px'><div style='border: 3px solid blue; width: 5%'><p>Lorem IpsumLorem IpsumLorem IpsumLor</p></div><div style='height: 50%'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-left: 8px; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; margin-right: 100%'><div style='width: 24%; height: 24px; margin-left: 10%; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 50px solid blue; margin-right: 100px; height: 3px; margin-right: 8%; width: 1%; width: 2px; border: 100% solid green; height: 24%'><div style='margin-left: auto'><p>Lorem IpsumLorem IpsumLo</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 24% solid green'><p>Lorem IpsumLore</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumL</p><p>Lorem IpsumLore</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='border: 50px solid blue; margin-right: 100px; height: 3px; margin-left: auto'><div style='margin-left: auto'><p>Lorem IpsumLorem IpsumLo</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 24% solid green'><p>Lorem IpsumLore</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumL</p><p>Lorem IpsumLore</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='border: 50px solid blue; margin-right: 100px; height: 3px; margin-right: 8%; width: 1%; width: 2px; border: 100% solid green; height: 24%'><div style='margin-left: auto'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLore</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumL</p><p>Lorem IpsumLore</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='height: 50px; width: 100%'><div style='margin-left: auto'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLore</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem </p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumL</p><p>Lorem IpsumLore</p><p>Lorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='height: 50px; width: 100%'><div style='margin-left: auto'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLore</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLo</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='height: 50px; width: 100%'><div style='margin-left: auto'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLore</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: 15px'><p>Lorem Ip</p></div><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ip</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem Ipsum</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div></body></html>",
  "<html><body><div style='height: 50px; width: 100%'><div style='margin-left: auto'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLore</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 2px; margin-left: auto; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='height: 50px; width: 100%'><div style='margin-left: auto'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 2px; margin-left: auto; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='height: 50px; width: 100%'><div style='margin-left: auto'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 2px; margin-left: auto; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='height: 50px; width: 100%'><div style='border: 3px solid blue; margin-left: 9px'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 2px; margin-left: auto; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='height: 50%; width: 100%'><div style='border: 3px solid blue; width: 100%'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-top: 24px; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 50px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 24%; height: 24px; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 2px solid green; width: 100%'><div style='border: 3px solid blue; width: 100%'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-left: auto; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 24%; height: 24px; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 2px solid green; width: 100%'><div style='border: 3px solid blue; width: 100%'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-left: auto; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 24%; height: 24px; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 2px solid green; width: 100%'><div style='border: 3px solid blue; width: 100%'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-left: auto; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLore</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 24%; height: 24px; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
  "<html><body><div style='border: 2px solid green; width: 100%'><div style='border: 3px solid blue; width: 100%'><p>Lorem IpsumL</p></div><div style='margin-left: 36px'><p>Lorem IpsumLore</p></div><div style='border: 2px solid blue; width: 50%; margin-left: auto; margin-right: auto'><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p><p>Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumL</p></div><div style='width: 24%; margin-right: 8px; margin-left: auto'><p>Lorem Ip</p></div><div style='border: 2px solid red; margin-top: 50px; width: 100%'><div style='width: 24%; height: 24px; margin-left: auto; margin-right: auto'><p>Lorem IpsumL</p></div></div></div></body></html>",
];
export function Home({}: Props) {
  const imageUrl = "/html_target.png";
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isStarted, setIsStarted] = useState(false);
  const [isFinished, setIsFinished] = useState(false);
  const intervalTime = 1500;

  const handleKeyPress = useCallback(
    (event: KeyboardEvent) => {
      if (event.code === "Space" && !isStarted) {
        setIsStarted(true);
      }
    },
    [isStarted]
  );

  useEffect(() => {
    window.addEventListener("keydown", handleKeyPress);
    return () => {
      window.removeEventListener("keydown", handleKeyPress);
    };
  }, [handleKeyPress]);

  useEffect(() => {
    let intervalId: number;
    if (isStarted) {
      intervalId = setInterval(() => {
        setCurrentIndex((prevIndex) => {
          const newIndex = Math.min(prevIndex + 1, expressions.length - 1);
          if (newIndex === expressions.length - 1) {
            setIsFinished(true);
            clearInterval(intervalId);
          }
          return newIndex;
        });
      }, intervalTime);
    }
    return () => clearInterval(intervalId);
  }, [isStarted]);

  useEffect(() => {
    console.log("Current Index: ", currentIndex);
  }, [currentIndex]);

  return (
    <div
      style={{
        display: "flex",
        width: "100%",
      }}
    >
      <div
        style={{
          width: "40%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{ marginBottom: "0px", textAlign: "center", width: "100%" }}
        >
          <div style={{ fontSize: "16px", marginBottom: "0px" }}>
            Target Image
          </div>
          <img
            src={imageUrl}
            alt="Uploaded Target"
            style={{
              maxWidth: "100%",
              maxHeight: "30vh",
              borderRadius: "8px",
              border: isFinished ? "3px solid #00c800" : "none",
            }}
          />
        </div>
        <div
          style={{
            width: "100%",
            fontFamily: "'Courier New', monospace",
            fontSize: "12px",
            whiteSpace: "wrap",
            backgroundColor: "#f4f4f4",
            borderRadius: "8px",
            marginBottom: "10px",
            border: "1px solid #ddd",
          }}
        >
          <div style={{ fontSize: "16px", marginBottom: "10px" }}>
            Expression
          </div>
          <CodeDisplay code={expressions[currentIndex]} />
        </div>
        <div
          style={{
            width: "100%",
            fontFamily: "'Courier New', monospace",
            fontSize: "12px",
            whiteSpace: "wrap",
            backgroundColor: "#fff",
            borderRadius: "8px",
          }}
        >
          <div style={{ fontSize: "16px", marginBottom: "10px" }}>
            Raw HTML Expression
          </div>
          <CodeDisplay code={html_expressions[currentIndex]} />
        </div>
      </div>
      <div
        style={{
          width: "60%",
          height: "90vh",
          padding: "10px",
          borderRadius: "8px",
          border: "1px solid #ddd",
          overflow: "hidden",
        }}
      >
        <div style={{ fontSize: "16px", textAlign: "center" }}>
          Rendered HTML
        </div>
        <div
          dangerouslySetInnerHTML={{ __html: html_expressions[currentIndex] }}
        ></div>
      </div>
    </div>
  );
}
